import spacy

nlp = spacy.load('en_core_web_sm')

about_text = ("Job Description: The administration of the district of Lörrach is located in the middle of the city of Lörrach, nestled between vineyards, Rhine and Wiesental and in direct Neighborhood to Switzerland with Basel and France with Alsace. Around 1,400 employees ensure the common good in the region. We not only manage - we shape the region with our work. are you included? Asylum Law Clerk (m/f/x) unlimited | full time | EG 9a TVöD Why we? - A varied and future-proof job at the earliest possible date time with a meaningful activity - A structured and comprehensive onboarding in the dedicated and open-minded team asylum law - The possibility of flexible and mobile working for a good Work-life balance - An open and fair culture with a high degree of creative freedom and modern workplaces - Modern training opportunities and active health management - Other benefits, such as B. a subsidy for the job ticket or the Possibility of a sabbatical What should I do? You will have the option of a permanent employment relationship an initially limited assignment until December 31, 2024 in the asylum law team. The main areas of focus for you are: - Issuance and extension of toleration and residence permits - Independent processing of applications for the granting and renewal of humanitarian residence permits - Processing of relocation requests (relocations of foreigners with residence requirement) - Identification service treatment of foreign persons - Written and oral hearings for incriminating administrative acts - Cooperation with other authorities (police, regional councils, etc.) - Intensive public traffic What does it take? - Training to become an administrative clerk, lawyer or Notary clerk, judicial clerk or a comparable one commercial qualification - Independent, result-oriented and structured way of working - Enjoy dealing with audience and team spirit - Confident demeanor, negotiation skills and assertiveness - High sense of responsibility and the ability to be appreciative and empathetic handling of the interlocutors - Good IT skills, especially in MS Office your way to us We look forward to receiving your application via our career portal by March 20, 2023 . Technical questions will be answered by: Mr. Bernd Wunderle, telephone: 07621 410-2340, e-mail: bernd.wunderle@loerrach-landkreis.de We will be happy to answer general questions: Mrs. Lena Bühler, telephone: 07621 410-1229, e-mail: lena.buehler@loerrach-landkreis.de Find more information about the district of Lörrach and about us as an employer She on our website: www.loerrach-landkreis.de")
about_doc = nlp(about_text)
sentences = list(about_doc.sents)
len(sentences)

for sentence in sentences:
    print(f"{sentence}")
